const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const btn=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=fn;return b;};
const test=new URLSearchParams(location.search).get('test')==='1';
const day=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul'}).format(new Date());
export async function healthCard(host,api,changed=()=>{}){
  const card=el('section',undefined,'growth-card');host.append(card);
  try{
    const [data,workspace]=await Promise.all([api('health'),api('workspace')]);if(!card.isConnected)return;
    card.append(el('h3','오늘 학습 여력'),el('p',data.score==null?'아직 점수를 계산할 기록이 부족합니다.':`${data.score} / 100 · 기록 ${data.coverage}항목 기준`),el('p',`수면 ${data.sleepHours==null?'미확인':data.sleepHours.toFixed(1)+'시간 · '+data.sleepSource} · 권장 공부 구간 ${data.blockMinutes}분`));
    const note=el('details');note.append(el('summary','계산 근거'),el('p',data.formula),el('p',data.note));card.append(note);
    const form=el('form'),fields=el('div',undefined,'growth-fields'),inputs={};
    for(const [key,label,min,max,step] of [['sleepH','수면 시간',0,24,.5],['fatigue','피로도 · 1 좋음, 5 지침',1,5,1],['focus','집중 가능 정도 · 0~10',0,10,1]]){const l=el('label',label),i=el('input');i.type='number';i.min=min;i.max=max;i.step=step;i.value=data.condition[key]??'';l.append(i);fields.append(l);inputs[key]=i;}
    const drink=el('select');for(const [v,t] of [['','음주 여부 미기록'],['no','전날 음주 안 함'],['yes','전날 음주함']]){const o=el('option',t);o.value=v;drink.append(o);}drink.value=data.condition.drankPrev==null?'':data.condition.drankPrev?'yes':'no';fields.append(drink);
    const memo=el('textarea');memo.rows=2;memo.maxLength=500;memo.placeholder='컨디션과 음주 시각·양, 불편함을 알려주세요.';memo.value=data.condition.note||'';memo.setAttribute('aria-label','오늘 컨디션 메모');const message=el('p'),save=btn('오늘 상태 저장',()=>{});save.type='submit';form.append(fields,memo,save,message);card.append(form);
    form.onsubmit=async e=>{e.preventDefault();save.disabled=true;const condition={note:memo.value,drankPrev:drink.value===''?null:drink.value==='yes'};for(const [k,i] of Object.entries(inputs))condition[k]=i.value===''?null:Number(i.value);try{await api('health',{date:day(),revision:workspace.revision,condition});card.remove();await healthCard(host,api,changed);changed();}catch(error){message.textContent=error.message;save.disabled=false;}};
  }catch(e){card.append(el('p',e.message),btn('다시 불러오기',()=>{card.remove();healthCard(host,api,changed);}));}
}
export function createGrowth(app){
  let live=null,session=null,lastInput=Date.now(),paused=true,queue=Promise.resolve(),lastStep='',attached=null,knownStages=new Map(),activityError='',courseCache=[];
  const strip=el('aside',undefined,'learning-strip');strip.hidden=true;document.querySelector('.school').insertBefore(strip,document.getElementById('scene'));
  const status=el('span'),pause=btn('일시정지',()=>paused?start(session):stop('pause'));strip.append(status,pause,btn('공부 종료',async()=>{await stop('finish');app.home();}),btn('내 스킬',showSkills));
  async function aw(path,body){if(test)return {active:null,version:0,records:[]};const r=await fetch('/api/aliveweek/'+path,{credentials:'same-origin',cache:'no-store',...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),keepalive:true}:{})});const data=await r.json();if(!r.ok)throw new Error(data.error||'학습 활동을 저장하지 못했습니다.');return data;}
  function activity(s){const c=[...app.courses(),...courseCache].find(c=>c.name===s.course);if(!c)return null;return {kind:s.taskKey?'task':'study',subjectId:c.id,...(s.taskKey?{taskKey:s.taskKey}:{}),label:`${s.course} · ${s.stepTitle||s.lessonTitle} · ${s.taskKey?'과제 작업':s.phase==='quiz'?'문제 풀이':s.phase==='example'?'예제 학습':'개념 학습'}`,schoolSessionId:s.id,...(s.lessonId?{lessonId:s.lessonId,stepId:s.stepId}:{}),phase:s.phase,place:s.course+(s.taskKey?' 과제실':' 교실')};}
  function redraw(){strip.hidden=!session;pause.textContent=paused?'공부 계속하기':'일시정지';status.className=activityError?'activity-warning':'';status.textContent=activityError||`${session?.course||''} · ${paused?'일시정지':test?'검증 모드 · 실제 활동 기록 안 함':'얼라이브위크에 학습 중 기록'}${!paused&&live?.active?' · '+Math.floor((Date.now()-Date.parse(live.active.startedAt))/60000)+'분':''}`;}
  function enqueue(fn){const task=queue.catch(()=>{}).then(fn);queue=task;return task;}
  async function start(s){if(!s)return;return enqueue(async()=>{session=s;if(!app.courses().length&&!courseCache.length)courseCache=(await app.api('workspace')).courses;const fields=activity(s);strip.hidden=false;if(!fields){activityError='현재 과목 연결을 확인해야 합니다.';redraw();return;}if(test){paused=false;redraw();return;}
    try{live=await aw('live');const current=live.active;if(current&&current.schoolSessionId!==s.id){activityError=`얼라이브위크에서 ‘${current.label}’ 진행 중 · 그 활동을 종료한 뒤 학습 기록을 시작하세요.`;paused=true;redraw();return;}
      const same=!!current&&current.lessonId===s.lessonId&&current.stepId===s.stepId&&current.taskKey===s.taskKey&&current.phase===s.phase;
      if(!same)live=await aw('live',{operationId:crypto.randomUUID(),expectedVersion:live.version,action:current?'switch':'start',...(current?{activityId:current.id}:{}),activity:fields});
      else live=await aw('live',{operationId:crypto.randomUUID(),expectedVersion:live.version,action:'heartbeat',activityId:current.id});
      paused=false;lastInput=Date.now();activityError='';redraw();
    }catch(e){paused=true;activityError=e.message;redraw();}});}
  async function stop(action='pause'){return enqueue(async()=>{if(paused){redraw();return;}try{if(!test){const latest=await aw('live');if(latest.active?.schoolSessionId===session?.id)live=await aw('live',{operationId:crypto.randomUUID(),expectedVersion:latest.version,action,activityId:latest.active.id});}paused=true;activityError='';redraw();}catch(e){activityError=e.message;redraw();throw e;}});}
  async function step(s){if(!s)return;session=s;strip.hidden=false;const key=s.id+'/'+s.stepId;if(key!==lastStep){lastStep=key;await start(s);}else redraw();}
  async function showSkills(){const host=app.panel('내 스킬 · 풀이 근거'),data=await app.api('growth');const grid=el('div',undefined,'growth-skills');host.append(el('p','서로 다른 확인 문제의 서버 채점과 도움 기록으로 판단합니다. AI 풀이 관찰은 자동 체득 판정에 쓰지 않습니다.'),grid);if(!data.skills.length)grid.append(el('p','확인한 스킬이 아직 없습니다. 개념을 배우고 직접 문제를 풀어보세요.'));
    for(const s of data.skills){const item=el('section',undefined,'skill-item'),p=el('progress');p.max=4;p.value=s.stage;item.append(el('b',s.name),el('p',s.course+' · '+s.label),p,el('p',s.next));const evidence=el('details');evidence.append(el('summary',`독립 풀이 근거 ${s.evidence.length}문제`));for(const e of s.evidence)evidence.append(btn(new Date(e.at*1000).toLocaleDateString('ko-KR')+' · 문제 다시 보기',()=>app.start(e.lesson,{stepId:e.step,purpose:'review'})));item.append(evidence);if(s.evidence[0])item.append(btn('조건이 다른 문제 연습',()=>app.retest(s.evidence.at(-1).lesson)));grid.append(item);}
  }
  async function notifySkills(){try{const data=await app.api('growth');for(const s of data.skills){const previous=knownStages.get(s.id);if(previous!==undefined&&s.stage>previous)app.status(`${s.name} · ${s.label} · 풀이 근거 ${s.evidence.length}문제`);knownStages.set(s.id,s.stage);}}catch{}}
  async function tutorPlan(host,data,refresh){
    attached=host;host.append(el('p','시험, 과제, 지난 풀이와 오늘 상태를 보고 스앵님이 계획을 세웁니다.'));
    healthCard(host,app.api,()=>refresh());const form=el('form'),input=el('textarea'),minutes=el('input');input.rows=2;input.maxLength=2000;input.placeholder='오늘 상황이나 막힌 부분을 말해주세요.';input.setAttribute('aria-label','오늘 상황');minutes.type='number';minutes.min=5;minutes.max=480;minutes.value=90;const l=el('label','오늘 공부할 수 있는 시간 · 분');l.append(minutes);const send=btn('스앵님이 오늘 계획 세우기',()=>{});send.type='submit';const result=el('div');form.append(input,l,send);host.append(form,result,btn('내 스킬 보기',showSkills));
    form.onsubmit=async e=>{e.preventDefault();send.disabled=true;result.replaceChildren(el('p','스앵님이 시험·풀이·컨디션을 확인하고 있습니다.'));try{const plan=await app.api('tutor-plan',{question:input.value,minutes:Number(minutes.value)});if(!host.isConnected)return;result.replaceChildren(el('p',plan.message));const start=el('input');start.type='time';start.required=true;const now=new Date(),k=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false}).format(now);start.value=k;const label=el('label','계획 시작 시각');label.append(start);result.append(label);
      for(const item of plan.items){const row=el('div',undefined,'tutor-plan-item');row.append(el('b',`${item.course} · ${item.minutes}분`),el('p',item.goal),el('small',item.reason+` · 이후 휴식 ${item.breakAfter}분`),btn('교실에서 시작',()=>app.start(item.lessonId,{purpose:'tutoring'})));result.append(row);}
      const message=el('p');result.append(btn('이 계획을 오늘 계획에 적용',async()=>{try{if(!/^\d\d:\d\d$/.test(start.value))throw new Error('시작 시각을 정해주세요.');let cursor=Number(start.value.slice(0,2))*60+Number(start.value.slice(3));const hm=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;const plans=plan.items.map(x=>{const s=cursor;cursor+=x.minutes;const end=cursor;cursor+=x.breakAfter;if(end>=1440)throw new Error('자정을 넘는 계획입니다. 시작 시각을 앞당겨주세요.');return {date:plan.date,s:hm(s),e:hm(end),courseId:x.courseId,note:x.goal+' · '+x.reason,kind:'시험 대비',lessonId:x.lessonId,tutorProposalId:plan.id};});const latest=await app.api('workspace');if(latest.revision!==plan.revision)throw new Error('계획 제안 후 기록이 바뀐 상태입니다. 스앵님과 다시 계획을 확인해주세요.');await app.api('workspace',{op:'plan-add',termId:latest.termId,revision:latest.revision,plans,consultation:true});message.textContent='얼라이브위크의 오늘 학습 계획에 저장했습니다.';refresh();}catch(error){message.textContent=error.message;}}),message);
    }catch(error){result.replaceChildren(el('p',error.message));}finally{send.disabled=false;}};
  }
  document.addEventListener('pointerdown',()=>lastInput=Date.now());document.addEventListener('keydown',()=>lastInput=Date.now());
  setInterval(async()=>{if(!session||paused)return;if(document.hidden||Date.now()-lastInput>180000){await stop('pause').catch(()=>{});activityError='입력이 없어 시간을 일시정지했습니다. 계속 공부하기를 눌러 이어가세요.';redraw();return;}if(!test)enqueue(async()=>{try{const latest=await aw('live');if(latest.active?.schoolSessionId!==session.id){paused=true;activityError='다른 화면에서 활동이 변경됐습니다. 현재 활동을 확인해주세요.';}else live=await aw('live',{operationId:crypto.randomUUID(),expectedVersion:latest.version,action:'heartbeat',activityId:latest.active.id});redraw();}catch(e){activityError=e.message;redraw();}});},30000);
  document.addEventListener('visibilitychange',()=>{if(document.hidden)stop('pause').catch(()=>{});});window.addEventListener('pagehide',()=>{if(test||paused||!live?.active)return;fetch('/api/aliveweek/live',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({operationId:crypto.randomUUID(),expectedVersion:live.version,action:'pause',activityId:live.active.id}),keepalive:true}).catch(()=>{});});
  async function task(row){await stop('pause');lastStep='';await start({id:'assignment-'+row.id,course:row.course,stepTitle:row.title,taskKey:'school-assignment|'+row.id,phase:'assignment'});}
  notifySkills();return {step,start,stop,task,showSkills,notifySkills,tutorPlan,healthCard:host=>healthCard(host,app.api)};
}
